openapi: 3.0.3
info:
  title: JarvisOps API
  version: 0.1.0
servers:
- url: http://localhost:8010
paths:
  /healthz:
    get:
      summary: health
      responses:
        '200':
          description: ok
  /v1/plan:
    post:
      summary: plan
      responses:
        '200':
          description: ok
  /v1/run:
    post:
      summary: run
      responses:
        '200':
          description: ok
  /v1/jobs/{job_id}:
    get:
      summary: job
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
  /v1/memory/append:
    post:
      summary: mem append
      responses:
        '200':
          description: ok
  /v1/memory/get:
    get:
      summary: mem get
      responses:
        '200':
          description: ok
